### ISSUE TITLE
有社区论坛吗？

### ISSUE THREAD

**Issue by cqh963852** [shank7server/Client#3]
我是一名全栈工程师，也是闪客快打玩家。闪客快打给了我愉快地童年游戏体验。

如果需要建设社区论坛，我可以提供免费技术支持。

**Comment by shank7server** [comment]
暂时不需要，谢谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;cqh&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月14日(星期三) 下午2:48
收件人:&nbsp;&quot;shank7server/Client&quot;<Client@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[shank7server/Client] 有社区论坛吗？ (#3)
